version: 0.0
os: linux
files:
 - source: /
   destination: /tmp/game-of-life

hooks:
  BeforeInstall:
    - location: scripts/clean-webdir.sh
      runas: root
  AfterInstall:
    - location: scripts/jetty-start.sh
      runas: root
